### ISSUE TITLE
хохлы пидорасы

### ISSUE THREAD

**Issue by 720pcod** [lkqas/UltimateTool#8]
salo = "хохлы пидорасы"
print(salo)

**Comment by AmokDEV** [comment]
@720pcod ХААХАХАХА

**Comment by AmokDEV** [comment]
@AmokDEV чтооо

**Comment by AmokDEV** [comment]
@AmokDEV print("Ликас, спасибо за детство")

**Comment by AmokDEV** [comment]
@AmokDEV штооооо

**Comment by AmokDEV** [comment]
а как ._.

**Comment by AmokDEV** [comment]
да

**Comment by AmokDEV** [comment]
го так в чате общаться?

**Comment by AmokDEV** [comment]
😄😁😁😁☺🥰😍😗😍

**Comment by iamnalinor** [comment]
@AmokDEV ПИЗДА 🤡🤡🤡

**Comment by AmokDEV** [comment]
@iamnalinor ДА КАК

**Comment by AmokDEV** [comment]
@AmokDEV откуда оно знает наши гитхуи

**Comment by lkqas** [comment]
@720pcod Долбоеб

**Comment by iamnalinor** [comment]
> @720pcod Долбоеб

злой (evil)

**Comment by lkqas** [comment]
@iamnalinor Не пиши тут, ебанутый
